spring.application.name=operation-service
server.port= 8082

# Database configuration for postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/smart_contract_db
spring.datasource.username=postgres
spring.datasource.password=080317st
spring.jpa.hibernate.ddl-auto=update